function phi = cal_phi(State,y0)
global C CC DD kv X0d
Cf = C;
dist = kv*(X0d-y0(3)); %l in the thesis

Xi = y0(1);
Yi = y0(2);
Xf = 1/2;
Yf = 1/2;
X = State(1);
Y = State(2);
%% calculated by mathematica
AA = (-1).*(dist+Xf+(-1).*Xi+Cf.*Yf+(-1).*Cf.*Yi).^(-1).*((-1)+DD.* ...
    dist.^2+2.*DD.*dist.*Xf+DD.*Xf.^2+(-1).*DD.*Xi.^2+2.*Cf.*DD.* ...
    dist.*Yf+2.*Cf.*DD.*Xf.*Yf+Cf.^2.*DD.*Yf.^2+CC.*dist.*Yi+(-2).* ...
    Cf.*DD.*dist.*Yi+CC.*Xf.*Yi+(-2).*Cf.*DD.*Xf.*Yi+(-1).*CC.*Xi.*Yi+ ...
    CC.*Cf.*Yf.*Yi+(-2).*Cf.^2.*DD.*Yf.*Yi+(-1).*CC.*Cf.*Yi.^2+Cf.^2.* ...
    DD.*Yi.^2);
BB = (-1).*(dist+Xf+(-1).*Xi+Cf.*Yf+(-1).*Cf.*Yi).^(-1).*((-1).*Cf+CC.* ...
    dist.^2+(-1).*Cf.*DD.*dist.^2+2.*CC.*dist.*Xf+(-2).*Cf.*DD.*dist.* ...
    Xf+CC.*Xf.^2+(-1).*Cf.*DD.*Xf.^2+(-1).*CC.*dist.*Xi+2.*Cf.*DD.* ...
    dist.*Xi+(-1).*CC.*Xf.*Xi+2.*Cf.*DD.*Xf.*Xi+(-1).*Cf.*DD.*Xi.^2+ ...
    2.*CC.*Cf.*dist.*Yf+(-2).*Cf.^2.*DD.*dist.*Yf+2.*CC.*Cf.*Xf.*Yf+( ...
    -2).*Cf.^2.*DD.*Xf.*Yf+(-1).*CC.*Cf.*Xi.*Yf+2.*Cf.^2.*DD.*Xi.*Yf+ ...
    CC.*Cf.^2.*Yf.^2+(-1).*Cf.^3.*DD.*Yf.^2+(-1).*CC.*Cf.*Xi.*Yi+(-1) ...
    .*CC.*Cf.^2.*Yi.^2+Cf.^3.*DD.*Yi.^2);
EE = CC.*Cf+(-1).*Cf.^2.*DD;
FF = (-1).*((-1).*dist+(-1).*Xf+Xi+(-1).*Cf.*Yf+Cf.*Yi).^(-1).*((-1).* ...
    Xi+DD.*dist.^2.*Xi+2.*DD.*dist.*Xf.*Xi+DD.*Xf.^2.*Xi+(-1).*DD.* ...
    dist.*Xi.^2+(-1).*DD.*Xf.*Xi.^2+2.*Cf.*DD.*dist.*Xi.*Yf+2.*Cf.* ...
    DD.*Xf.*Xi.*Yf+(-1).*Cf.*DD.*Xi.^2.*Yf+Cf.^2.*DD.*Xi.*Yf.^2+(-1).* ...
    Cf.*Yi+CC.*dist.^2.*Yi+(-1).*Cf.*DD.*dist.^2.*Yi+2.*CC.*dist.*Xf.* ...
    Yi+(-2).*Cf.*DD.*dist.*Xf.*Yi+CC.*Xf.^2.*Yi+(-1).*Cf.*DD.*Xf.^2.* ...
    Yi+(-1).*CC.*dist.*Xi.*Yi+(-1).*CC.*Xf.*Xi.*Yi+2.*CC.*Cf.*dist.* ...
    Yf.*Yi+(-2).*Cf.^2.*DD.*dist.*Yf.*Yi+2.*CC.*Cf.*Xf.*Yf.*Yi+(-2).* ...
    Cf.^2.*DD.*Xf.*Yf.*Yi+(-1).*CC.*Cf.*Xi.*Yf.*Yi+CC.*Cf.^2.*Yf.^2.* ...
    Yi+(-1).*Cf.^3.*DD.*Yf.^2.*Yi+(-1).*CC.*Cf.*dist.*Yi.^2+Cf.^2.* ...
    DD.*dist.*Yi.^2+(-1).*CC.*Cf.*Xf.*Yi.^2+Cf.^2.*DD.*Xf.*Yi.^2+(-1) ...
    .*CC.*Cf.^2.*Yf.*Yi.^2+Cf.^3.*DD.*Yf.*Yi.^2);
%%

phi = AA*X + BB*Y + CC*X*Y+DD*X^2+EE*Y^2+FF;

end